# moNa2 v2 — dongle mode
# Dongle: Makerdiary nRF52840 MDK USB Dongle (split central, USB to host)
# Halves: Seeed XIAO nRF52840 (split peripherals)
---
include:
  - board: nrf52840_mdk_usb_dongle
    shield: mona2_dongle mdk_dongle rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: mona2_dongle
  - board: seeeduino_xiao_ble
    shield: mona2_r rgbled_adapter
    artifact-name: mona2_right
  - board: seeeduino_xiao_ble
    shield: mona2_l rgbled_adapter
    artifact-name: mona2_left
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao
  - board: nrf52840_mdk_usb_dongle
    shield: settings_reset mdk_dongle
    artifact-name: settings_reset_dongle
