#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y

#Bluetooth config -------------------
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
